/*
**
 * Author:  EUTUXIA
 * Created: 19/12/2019
 */

CREATE DATABASE EUROCHEM;

USE EUROCHEM;

-- CREACION DE TABLAS

CREATE TABLE UNIDADES(
    ID INT AUTO_INCREMENT,
    UNIDAD VARCHAR(30),
    
    PRIMARY KEY (ID)
);

CREATE TABLE DIVISIONES(
    ID INT AUTO_INCREMENT,
    DIVISION VARCHAR(30),
    
    PRIMARY KEY (ID)
);

CREATE TABLE INDUSTRIAS(
    ID INT AUTO_INCREMENT,
    INDUSTRIA VARCHAR(100),
    
    PRIMARY KEY (ID)
);

CREATE TABLE TIPO_PRODUCTOS(
    ID INT AUTO_INCREMENT,
    TIPO_PRODUCTO VARCHAR(255),
    
    PRIMARY KEY (ID)
);

CREATE TABLE PRESENTACIONES(
    ID INT AUTO_INCREMENT,
    PRESENTACION VARCHAR(255),
    
    PRIMARY KEY (ID)
);

CREATE TABLE PRODUCTOS(
    ID INT AUTO_INCREMENT,
    TITULO VARCHAR(255),
    SUBTITULO VARCHAR(255),
    DESCRIPCION TEXT,
    SKU VARCHAR(50),
    IDDIVISION INT,
    IDPRESENTACION INT,
    IDUNIDAD INT,
    IDTIPOPRODUCTO INT,
    URL_TEMP TEXT,

    PRIMARY KEY (ID)
);

CREATE TABLE PRODUCTOS_INDUSTRIAS(
    IDPRODUCTO INT,
    IDINDUSTRIA INT,

    FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS(ID)
    ON DELETE CASCADE,
    FOREIGN KEY (IDINDUSTRIA) REFERENCES INDUSTRIAS(ID)
    ON DELETE CASCADE    

);

CREATE TABLE OTROS_NOMBRES(
    ID INT AUTO_INCREMENT,
    OTRO_NOMBRE VARCHAR(255),
    
    PRIMARY KEY (ID)
);

CREATE TABLE PRODUCTOS_OTROS_NOMBRES(
    IDPRODUCTO INT,
    IDOTRONOMBRE INT,

    FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS(ID)
    ON DELETE CASCADE,
    FOREIGN KEY (IDOTRONOMBRE) REFERENCES OTROS_NOMBRES(ID)
    ON DELETE CASCADE    

);

CREATE TABLE FICHA_TECNICA(
    ID INT AUTO_INCREMENT,
    IDPRODUCTO INT, 
    FECHA TIMESTAMP, 
    FORMULA VARCHAR(100),
    NOMBRE_COMERCIAL TEXT,
    PESO_MOLECULAR VARCHAR(50),
    SINONIMOS TEXT,
    DESCRIPCION TEXT,
    USOS TEXT,
    PIE_PAGINA TEXT,

    PRIMARY KEY (ID),
    FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS(ID)
    ON DELETE CASCADE

);

CREATE TABLE ESPECIFICACIONES_TECNICAS(
    ID INT AUTO_INCREMENT,
    IDFICHATECNICA INT, 
    PROPIEDAD VARCHAR(100),
    UNIDAD VARCHAR(100),
    ESPECIFICACION VARCHAR(100),

    PRIMARY KEY (ID),
    FOREIGN KEY (IDFICHATECNICA) REFERENCES FICHA_TECNICA(ID) 
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ARTICLESBLOG(
  IDARTICULO INT AUTO_INCREMENT,
  TITLE varchar(255),
  IMAGE varchar(255),
  DESCRIPTION varchar(255),
  CONTENT text,
  KEYWORDS varchar(255),
  AUTOR varchar(255),
  DATE TIMESTAMP,

   PRIMARY KEY (IDARTICULO),
   UNIQUE (TITLE)
);

CREATE TABLE USUARIOS(
    IDUSUARIO INT AUTO_INCREMENT,
    NOMBRE VARCHAR(25),
    CORREO VARCHAR(30),
    CLAVE VARCHAR(50),
    NIVEL  INT,
    CREADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (IDUSUARIO),
    UNIQUE (CORREO)
)